### ISSUE TITLE
Sintáxis/Código

### ISSUE THREAD

**Issue by lucasjaviluna** [maurojjzz/Veterinaria-front-end#13]
[Low]
	- Hay muchos console.log
	- En el form de login no veo que muestren un loader/spinner mientras se está realizando la autenticación. Lo tienen?
	- Estos componentes están incompletos?
	https://vscode.dev/github/maurojjzz/Veterinaria-front-end/blob/master/src/Components/Users/User/index.jsx#L3
	https://vscode.dev/github/maurojjzz/Veterinaria-front-end/blob/master/src/Components/Users/Admin/Users/index.jsx#L3
	https://vscode.dev/github/maurojjzz/Veterinaria-front-end/blob/master/src/Components/Users/Veterinario/index.jsx
	https://vscode.dev/github/maurojjzz/Veterinaria-front-end/blob/master/src/Components/Users/Admin/Especies/index.jsx

**Comment by maurojjzz** [comment]
Si, la autenticacion esta completa. Tuve problemas con mi pc y me atrase con el desarrollo. Pero ya lo tengo hecho y esta noche mergeo la pr.
